- name: configuring redis component 
  hosts: redis 
  become: yes 
  tasks: 
  - name: disabling default redis 
    ansible.builtin.command: dnf module disable redis -y
  
  - name: enabling required redis version 
    ansible.builtin.command: dnf module enable redis:7 -y
  
  - name: installing redis 
    ansible.builtin.package: 
      name: redis 
      state: present 
      